### ISSUE TITLE
KeyError when using --filter all

### ISSUE THREAD

**Issue by LennertVerboven** [MDU-PHL/who2tbp#3]
When using the 'all' filter option I get the following error:

PS C:\Users\Lennert\workspaces\who2tbp> who2tbp --filter all WHO-UCN-GTB-PCI-2021.7-eng.xlsx > tbdb_who.py
[who2tbp.exe – 2021-07-16 09:27:48,582]: Welcome to who2tbp.exe
[who2tbp.exe – 2021-07-16 09:27:48,582]: Processing Excel file...
Traceback (most recent call last):
  File "c:\users\lennert\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lennert\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lennert\Anaconda3\Scripts\who2tbp.exe\__main__.py", line 9, in <module>
  File "c:\users\lennert\anaconda3\lib\site-packages\who2tbp\bin\main.py", line 39, in main
    data = parse_file(args.INFILE, this_filter=args.filter)
  File "c:\users\lennert\anaconda3\lib\site-packages\who2tbp\lib\parse_excel_data.py", line 37, in parse_file
    conf_class = [CONF_CLASSES[this_filter]]
KeyError: 'all'

This seems to be cause by the test on the following line which test 'filter' instead of 'this_filter'

https://github.com/MDU-PHL/who2tbp/blob/7947cbe0e57218cdba2e21171b3099dbee857f71/who2tbp/lib/parse_excel_data.py#L34

**Comment by andersgs** [comment]
Thank you @LennertVerboven. 

I would not encourage the use of `all` just yet. There are a number of edge cases that I don't think will be translated correctly yet.
